### ISSUE TITLE
ecto.rollback(:mariaex) - Cannot drop index 'xxxx_index': needed in a foreign key constraint

### ISSUE THREAD

**Issue by UeshibaKyohei** [phoenixframework/phoenix_ecto#49]
(* I'm sorry. I can't speak english )

* MySQL Community Server (GPL) - 5.7.12
* OSX10.11   (x86_64)
* Elixir 1.2.4

```
$ mix -v
Mix 1.2.4

$ mix deps
* connection 1.0.2 (Hex package) (mix)
  locked at 1.0.2 (connection)
  ok
* fs 0.9.1 (Hex package) (rebar)
  locked at 0.9.2 (fs)
  ok
* gettext 0.11.0 (Hex package) (mix)
  locked at 0.11.0 (gettext)
  ok
* ranch 1.2.1 (Hex package) (rebar)
  locked at 1.2.1 (ranch)
  ok
* poolboy 1.5.1 (Hex package) (rebar)
  locked at 1.5.1 (poolboy)
  ok
* decimal 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (decimal)
  ok
* poison 1.5.2 (Hex package) (mix)
  locked at 1.5.2 (poison)
  ok
* db_connection 0.2.5 (Hex package) (mix)
  locked at 0.2.5 (db_connection)
  ok
* cowlib 1.0.2 (Hex package) (rebar)
  locked at 1.0.2 (cowlib)
  ok
* cowboy 1.0.4 (Hex package) (rebar)
  locked at 1.0.4 (cowboy)
  ok
* plug 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (plug)
  ok
* phoenix_html 2.5.1 (Hex package) (mix)
  locked at 2.5.1 (phoenix_html)
  ok
* phoenix 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (phoenix)
  ok
* phoenix_live_reload 1.0.5 (Hex package) (mix)
  locked at 1.0.5 (phoenix_live_reload)
  ok
* mariaex 0.7.4 (Hex package) (mix)
  locked at 0.7.4 (mariaex)
  ok
* ecto 1.1.4 (Hex package) (mix)
  locked at 1.1.4 (ecto)
  ok
* phoenix_ecto 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (phoenix_ecto)
  ok
```

## STEP1 - Create *User* data
```
$ mix phoenix.gen.html User users name:string
...
...
$ mix ecto.migrate
```

## STEP2 - Create *Movie* data
- An associated User
- A title
```
$ mix phoenix.gen.html Movie movies user_id:references:users title:string
...
...
$ mix ecto.migrate
```

## STEP3 - Mariaex.Error
```
$ mix ecto.rollback

15:39:41.618 [info]  == Running EctoDropTest.Repo.Migrations.CreateMovie.change/0 backward

15:39:41.618 [info]  drop index movies_user_id_index
** (Mariaex.Error) (1553): Cannot drop index 'movies_user_id_index': needed in a foreign key constraint
    (ecto) lib/ecto/adapters/sql.ex:185: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/mysql.ex:85: anonymous fn/4 in Ecto.Adapters.MySQL.execute_ddl/3
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/mysql.ex:85: Ecto.Adapters.MySQL.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:89: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:87: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:26: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:121: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:101: anonymous fn/4 in Ecto.Migrator.do_down/4
    (ecto) lib/ecto/migrator.ex:227: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.rollback.ex:64: anonymous fn/4 in Mix.Tasks.Ecto.Rollback.run/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Is this a known issue or there is something wrong with my app?
Thank you!!

**Comment by josevalim** [comment]
That's how foreign keys work. :) You cannot remove a foreign key if there are associated records. Here is an alternative if you want to ignore those checks (although be careful if you do): https://gauravsohoni.wordpress.com/2009/03/09/mysql-disable-foreign-key-checks-or-constraints/

**Comment by UeshibaKyohei** [comment]
Thank you very much for your prompt responses.

But, it can not be resolved at that information.

mysql >= v5.6.x
```
mysql> create table t1 (id int not null primary key, name varchar(100) not null);

mysql> create table t2 (id int not null primary key, fid int not null, name varchar(100) not null, CONSTRAINT `fk_fid`

mysql> set foreign_key_checks=OFF

mysql> show variables like 'foreign_key_checks';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| foreign_key_checks | OFF   |
+--------------------+-------+
1 row in set (0.00 sec)


mysql> ALTER TABLE t2 DROP INDEX `fk_fid`;
ERROR 1553 (HY000): Cannot drop index 'fk_fid': needed in a foreign key constraint
```

There is no effect of the option(foreign_key_checks)!

* means

```
mysql> set foreign_key_checks=ON

mysql> show variables like 'foreign_key_checks';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| foreign_key_checks | ON   |
+--------------------+-------+
1 row in set (0.00 sec)


mysql> ALTER TABLE t2 DROP FOREIGN KEY `fk_fid`;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE t2 DROP INDEX `fk_fid`;
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

```

"mix ecto.rollback" can not be used in Mysql>=5.6.x

Please consider this matter.

**Comment by josevalim** [comment]
Can you please paste your migration? There is nothing Ecto can do, that is coming from your database. You cannot remove an INDEX if the INDEX is used by a foreign key. You need to first remove the foreign key, then you can remove the INDEX.

**Comment by UeshibaKyohei** [comment]
Thank you very much for your prompt responses.

I want to use '$ mix ecto.migrate / ecto.rollback'. So it has been changed as follows:

* before
```
$ mix phoenix.gen.html Movie movies user_id:references:users title:string
```

* after
```
$ mix phoenix.gen.html Movie movies user_id:integer title:string
```
I will later to set the 'foreign-key' by mysql client.

どうもありがとうございます。
