### ISSUE TITLE
CaseClauseError v3.0

### ISSUE THREAD

**Issue by craig-day** [phoenixframework/phoenix_ecto#57]
I have v3 declared as a dependency in my project, `{:phoenix_ecto, "~> 3.0"}`, but when trying to compile it get a `CaseClauseError`. 

```
==> phoenix_ecto
Compiled lib/phoenix_ecto.ex
Compiled lib/phoenix_ecto/plug.ex
Compiled lib/phoenix_ecto/sql/sandbox.ex
Compiled lib/phoenix_ecto/html.ex
Generated phoenix_ecto app
** (CaseClauseError) no case clause matching: {:error, :tokens}
    (kernel) file.erl:1368: :file.consult_stream/3
    (kernel) file.erl:978: :file.consult/1
    (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
    (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
    (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
    (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
    (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

here is my complete dependency list. 

```elixir
  defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:mariaex, ">= 0.0.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:phoenix_html, "~> 2.4"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:memcache_client, "~> 1.0.0"},
     {:credo, "~> 0.4", only: [:dev, :test]}]
  end
```

**Comment by craig-day** [comment]
Nevermind I guess. Sorry for the issue, must be something with my local config.  It builds fine elsewhere.
